-- FashionOS Enterprise — Permission catalog supplement
-- Synced from lib/core/permissions/permission_codes.dart
-- Run via supabase/seed.sql after 01_global_catalog.sql

INSERT INTO public.permissions (code, name, module, description) VALUES
  ('accounting.manage', 'Accounting Manage', 'accounting', 'Enterprise permission: accounting.manage'),
  ('accounting.view', 'Accounting View', 'accounting', 'Enterprise permission: accounting.view'),
  ('admin.manage', 'Admin Manage', 'admin', 'Enterprise permission: admin.manage'),
  ('admin.view', 'Admin View', 'admin', 'Enterprise permission: admin.view'),
  ('ai.view', 'Ai View', 'ai', 'Enterprise permission: ai.view'),
  ('analytics.manage', 'Analytics Manage', 'analytics', 'Enterprise permission: analytics.manage'),
  ('analytics.view', 'Analytics View', 'analytics', 'Enterprise permission: analytics.view'),
  ('apikey.manage', 'Apikey Manage', 'apikey', 'Enterprise permission: apikey.manage'),
  ('approval.manage', 'Approval Manage', 'approval', 'Enterprise permission: approval.manage'),
  ('approval.view', 'Approval View', 'approval', 'Enterprise permission: approval.view'),
  ('assets.maintenance.manage', 'Assets Maintenance Manage', 'assets', 'Enterprise permission: assets.maintenance.manage'),
  ('assets.maintenance.view', 'Assets Maintenance View', 'assets', 'Enterprise permission: assets.maintenance.view'),
  ('assets.manage', 'Assets Manage', 'assets', 'Enterprise permission: assets.manage'),
  ('assets.view', 'Assets View', 'assets', 'Enterprise permission: assets.view'),
  ('attendance.manage', 'Attendance Manage', 'attendance', 'Enterprise permission: attendance.manage'),
  ('audit.explore', 'Audit Explore', 'audit', 'Enterprise permission: audit.explore'),
  ('automation.approval.manage', 'Automation Approval Manage', 'automation', 'Enterprise permission: automation.approval.manage'),
  ('automation.manage', 'Automation Manage', 'automation', 'Enterprise permission: automation.manage'),
  ('automation.view', 'Automation View', 'automation', 'Enterprise permission: automation.view'),
  ('bank.manage', 'Bank Manage', 'bank', 'Enterprise permission: bank.manage'),
  ('bank.reconcile', 'Bank Reconcile', 'bank', 'Enterprise permission: bank.reconcile'),
  ('bom.manage', 'Bom Manage', 'bom', 'Enterprise permission: bom.manage'),
  ('brand.create', 'Brand Create', 'brand', 'Enterprise permission: brand.create'),
  ('brand.delete', 'Brand Delete', 'brand', 'Enterprise permission: brand.delete'),
  ('brand.manage', 'Brand Manage', 'brand', 'Enterprise permission: brand.manage'),
  ('brand.read', 'Brand Read', 'brand', 'Enterprise permission: brand.read'),
  ('brand.update', 'Brand Update', 'brand', 'Enterprise permission: brand.update'),
  ('cash.manage', 'Cash Manage', 'cash', 'Enterprise permission: cash.manage'),
  ('category.create', 'Category Create', 'category', 'Enterprise permission: category.create'),
  ('category.delete', 'Category Delete', 'category', 'Enterprise permission: category.delete'),
  ('category.manage', 'Category Manage', 'category', 'Enterprise permission: category.manage'),
  ('category.read', 'Category Read', 'category', 'Enterprise permission: category.read'),
  ('category.update', 'Category Update', 'category', 'Enterprise permission: category.update'),
  ('cheque.manage', 'Cheque Manage', 'cheque', 'Enterprise permission: cheque.manage'),
  ('commission.manage', 'Commission Manage', 'commission', 'Enterprise permission: commission.manage'),
  ('connector.manage', 'Connector Manage', 'connector', 'Enterprise permission: connector.manage'),
  ('coupon.manage', 'Coupon Manage', 'coupon', 'Enterprise permission: coupon.manage'),
  ('credit.manage', 'Credit Manage', 'credit', 'Enterprise permission: credit.manage'),
  ('customer.create', 'Customer Create', 'customer', 'Enterprise permission: customer.create'),
  ('customer.delete', 'Customer Delete', 'customer', 'Enterprise permission: customer.delete'),
  ('customer.update', 'Customer Update', 'customer', 'Enterprise permission: customer.update'),
  ('customer.view', 'Customer View', 'customer', 'Enterprise permission: customer.view'),
  ('dashboard.manage', 'Dashboard Manage', 'dashboard', 'Enterprise permission: dashboard.manage'),
  ('delivery.manage', 'Delivery Manage', 'delivery', 'Enterprise permission: delivery.manage'),
  ('depreciation.manage', 'Depreciation Manage', 'depreciation', 'Enterprise permission: depreciation.manage'),
  ('disposal.manage', 'Disposal Manage', 'disposal', 'Enterprise permission: disposal.manage'),
  ('employee.manage', 'Employee Manage', 'employee', 'Enterprise permission: employee.manage'),
  ('exchange.manage', 'Exchange Manage', 'exchange', 'Enterprise permission: exchange.manage'),
  ('executive.dashboard', 'Executive Dashboard', 'executive', 'Enterprise permission: executive.dashboard'),
  ('expense.manage', 'Expense Manage', 'expense', 'Enterprise permission: expense.manage'),
  ('featureflag.manage', 'Featureflag Manage', 'featureflag', 'Enterprise permission: featureflag.manage'),
  ('fiscal.close', 'Fiscal Close', 'fiscal', 'Enterprise permission: fiscal.close'),
  ('forecast.view', 'Forecast View', 'forecast', 'Enterprise permission: forecast.view'),
  ('giftreceipt.create', 'Giftreceipt Create', 'giftreceipt', 'Enterprise permission: giftreceipt.create'),
  ('hr.manage', 'Hr Manage', 'hr', 'Enterprise permission: hr.manage'),
  ('hr.view', 'Hr View', 'hr', 'Enterprise permission: hr.view'),
  ('integrations.manage', 'Integrations Manage', 'integrations', 'Enterprise permission: integrations.manage'),
  ('integrations.view', 'Integrations View', 'integrations', 'Enterprise permission: integrations.view'),
  ('inventory.adjust', 'Inventory Adjust', 'inventory', 'Enterprise permission: inventory.adjust'),
  ('inventory.count', 'Inventory Count', 'inventory', 'Enterprise permission: inventory.count'),
  ('inventory.movement', 'Inventory Movement', 'inventory', 'Enterprise permission: inventory.movement'),
  ('inventory.read', 'Inventory Read', 'inventory', 'Enterprise permission: inventory.read'),
  ('inventory.transfer.approve', 'Inventory Transfer Approve', 'inventory', 'Enterprise permission: inventory.transfer.approve'),
  ('inventory.transfer.create', 'Inventory Transfer Create', 'inventory', 'Enterprise permission: inventory.transfer.create'),
  ('inventory.transfer.receive', 'Inventory Transfer Receive', 'inventory', 'Enterprise permission: inventory.transfer.receive'),
  ('invoice.create', 'Invoice Create', 'invoice', 'Enterprise permission: invoice.create'),
  ('journal.create', 'Journal Create', 'journal', 'Enterprise permission: journal.create'),
  ('journal.post', 'Journal Post', 'journal', 'Enterprise permission: journal.post'),
  ('journal.reverse', 'Journal Reverse', 'journal', 'Enterprise permission: journal.reverse'),
  ('kpi.view', 'Kpi View', 'kpi', 'Enterprise permission: kpi.view'),
  ('layaway.manage', 'Layaway Manage', 'layaway', 'Enterprise permission: layaway.manage'),
  ('leave.manage', 'Leave Manage', 'leave', 'Enterprise permission: leave.manage'),
  ('ledger.view', 'Ledger View', 'ledger', 'Enterprise permission: ledger.view'),
  ('loyalty.manage', 'Loyalty Manage', 'loyalty', 'Enterprise permission: loyalty.manage'),
  ('manufacturing.maintenance.manage', 'Manufacturing Maintenance Manage', 'manufacturing', 'Enterprise permission: manufacturing.maintenance.manage'),
  ('manufacturing.manage', 'Manufacturing Manage', 'manufacturing', 'Enterprise permission: manufacturing.manage'),
  ('manufacturing.view', 'Manufacturing View', 'manufacturing', 'Enterprise permission: manufacturing.view'),
  ('notification.manage', 'Notification Manage', 'notification', 'Enterprise permission: notification.manage'),
  ('notification.view', 'Notification View', 'notification', 'Enterprise permission: notification.view'),
  ('org.manage', 'Org Manage', 'org', 'Enterprise permission: org.manage'),
  ('payment.manage', 'Payment Manage', 'payment', 'Enterprise permission: payment.manage'),
  ('payroll.approve', 'Payroll Approve', 'payroll', 'Enterprise permission: payroll.approve'),
  ('payroll.manage', 'Payroll Manage', 'payroll', 'Enterprise permission: payroll.manage'),
  ('payroll.view', 'Payroll View', 'payroll', 'Enterprise permission: payroll.view'),
  ('performance.manage', 'Performance Manage', 'performance', 'Enterprise permission: performance.manage'),
  ('planning.manage', 'Planning Manage', 'planning', 'Enterprise permission: planning.manage'),
  ('product.archive', 'Product Archive', 'product', 'Enterprise permission: product.archive'),
  ('product.bulk', 'Product Bulk', 'product', 'Enterprise permission: product.bulk'),
  ('product.create', 'Product Create', 'product', 'Enterprise permission: product.create'),
  ('product.delete', 'Product Delete', 'product', 'Enterprise permission: product.delete'),
  ('product.export', 'Product Export', 'product', 'Enterprise permission: product.export'),
  ('product.import', 'Product Import', 'product', 'Enterprise permission: product.import'),
  ('product.read', 'Product Read', 'product', 'Enterprise permission: product.read'),
  ('product.update', 'Product Update', 'product', 'Enterprise permission: product.update'),
  ('product.variant.manage', 'Product Variant Manage', 'product', 'Enterprise permission: product.variant.manage'),
  ('production.complete', 'Production Complete', 'production', 'Enterprise permission: production.complete'),
  ('production.create', 'Production Create', 'production', 'Enterprise permission: production.create'),
  ('production.release', 'Production Release', 'production', 'Enterprise permission: production.release'),
  ('purchase.approve', 'Purchase Approve', 'purchase', 'Enterprise permission: purchase.approve'),
  ('purchase.cancel', 'Purchase Cancel', 'purchase', 'Enterprise permission: purchase.cancel'),
  ('purchase.close', 'Purchase Close', 'purchase', 'Enterprise permission: purchase.close'),
  ('purchase.create', 'Purchase Create', 'purchase', 'Enterprise permission: purchase.create'),
  ('purchase.payment', 'Purchase Payment', 'purchase', 'Enterprise permission: purchase.payment'),
  ('purchase.receive', 'Purchase Receive', 'purchase', 'Enterprise permission: purchase.receive'),
  ('purchase.report', 'Purchase Report', 'purchase', 'Enterprise permission: purchase.report'),
  ('purchase.return.approve', 'Purchase Return Approve', 'purchase', 'Enterprise permission: purchase.return.approve'),
  ('purchase.return.create', 'Purchase Return Create', 'purchase', 'Enterprise permission: purchase.return.create'),
  ('purchase.send', 'Purchase Send', 'purchase', 'Enterprise permission: purchase.send'),
  ('purchase.update', 'Purchase Update', 'purchase', 'Enterprise permission: purchase.update'),
  ('purchase.view', 'Purchase View', 'purchase', 'Enterprise permission: purchase.view'),
  ('quality.manage', 'Quality Manage', 'quality', 'Enterprise permission: quality.manage'),
  ('quotation.approve', 'Quotation Approve', 'quotation', 'Enterprise permission: quotation.approve'),
  ('quotation.create', 'Quotation Create', 'quotation', 'Enterprise permission: quotation.create'),
  ('receipt.manage', 'Receipt Manage', 'receipt', 'Enterprise permission: receipt.manage'),
  ('receipt.reprint', 'Receipt Reprint', 'receipt', 'Enterprise permission: receipt.reprint'),
  ('reconciliation.manage', 'Reconciliation Manage', 'reconciliation', 'Enterprise permission: reconciliation.manage'),
  ('reports.create', 'Reports Create', 'reports', 'Enterprise permission: reports.create'),
  ('reports.export', 'Reports Export', 'reports', 'Enterprise permission: reports.export'),
  ('reports.financial', 'Reports Financial', 'reports', 'Enterprise permission: reports.financial'),
  ('reports.schedule', 'Reports Schedule', 'reports', 'Enterprise permission: reports.schedule'),
  ('reports.tax', 'Reports Tax', 'reports', 'Enterprise permission: reports.tax'),
  ('reports.view', 'Reports View', 'reports', 'Enterprise permission: reports.view'),
  ('return.manage', 'Return Manage', 'return', 'Enterprise permission: return.manage'),
  ('role.admin', 'Role Admin', 'role', 'Enterprise permission: role.admin'),
  ('rule.manage', 'Rule Manage', 'rule', 'Enterprise permission: rule.manage'),
  ('sale.cancel', 'Sale Cancel', 'sale', 'Enterprise permission: sale.cancel'),
  ('sale.cash', 'Sale Cash', 'sale', 'Enterprise permission: sale.cash'),
  ('sale.close_session', 'Sale Close Session', 'sale', 'Enterprise permission: sale.close_session'),
  ('sale.create', 'Sale Create', 'sale', 'Enterprise permission: sale.create'),
  ('sale.discount', 'Sale Discount', 'sale', 'Enterprise permission: sale.discount'),
  ('sale.exchange', 'Sale Exchange', 'sale', 'Enterprise permission: sale.exchange'),
  ('sale.override_price', 'Sale Override Price', 'sale', 'Enterprise permission: sale.override_price'),
  ('sale.payment', 'Sale Payment', 'sale', 'Enterprise permission: sale.payment'),
  ('sale.print', 'Sale Print', 'sale', 'Enterprise permission: sale.print'),
  ('sale.refund', 'Sale Refund', 'sale', 'Enterprise permission: sale.refund'),
  ('sale.update', 'Sale Update', 'sale', 'Enterprise permission: sale.update'),
  ('sale.view', 'Sale View', 'sale', 'Enterprise permission: sale.view'),
  ('sales.approve', 'Sales Approve', 'sales', 'Enterprise permission: sales.approve'),
  ('sales.manage', 'Sales Manage', 'sales', 'Enterprise permission: sales.manage'),
  ('sales.view', 'Sales View', 'sales', 'Enterprise permission: sales.view'),
  ('scheduler.manage', 'Scheduler Manage', 'scheduler', 'Enterprise permission: scheduler.manage'),
  ('security.manage', 'Security Manage', 'security', 'Enterprise permission: security.manage'),
  ('shipment.manage', 'Shipment Manage', 'shipment', 'Enterprise permission: shipment.manage'),
  ('supplier.create', 'Supplier Create', 'supplier', 'Enterprise permission: supplier.create'),
  ('supplier.delete', 'Supplier Delete', 'supplier', 'Enterprise permission: supplier.delete'),
  ('supplier.update', 'Supplier Update', 'supplier', 'Enterprise permission: supplier.update'),
  ('supplier.view', 'Supplier View', 'supplier', 'Enterprise permission: supplier.view'),
  ('system.maintenance.manage', 'System Maintenance Manage', 'system', 'Enterprise permission: system.maintenance.manage'),
  ('system.manage', 'System Manage', 'system', 'Enterprise permission: system.manage'),
  ('system.view', 'System View', 'system', 'Enterprise permission: system.view'),
  ('tenant.settings', 'Tenant Settings', 'tenant', 'Enterprise permission: tenant.settings'),
  ('transfer.manage', 'Transfer Manage', 'transfer', 'Enterprise permission: transfer.manage'),
  ('treasury.bank.manage', 'Treasury Bank Manage', 'treasury', 'Enterprise permission: treasury.bank.manage'),
  ('treasury.manage', 'Treasury Manage', 'treasury', 'Enterprise permission: treasury.manage'),
  ('treasury.receipt.manage', 'Treasury Receipt Manage', 'treasury', 'Enterprise permission: treasury.receipt.manage'),
  ('treasury.view', 'Treasury View', 'treasury', 'Enterprise permission: treasury.view'),
  ('user.admin', 'User Admin', 'user', 'Enterprise permission: user.admin'),
  ('wallet.manage', 'Wallet Manage', 'wallet', 'Enterprise permission: wallet.manage'),
  ('warehouse.create', 'Warehouse Create', 'warehouse', 'Enterprise permission: warehouse.create'),
  ('warehouse.delete', 'Warehouse Delete', 'warehouse', 'Enterprise permission: warehouse.delete'),
  ('warehouse.update', 'Warehouse Update', 'warehouse', 'Enterprise permission: warehouse.update'),
  ('warehouse.view', 'Warehouse View', 'warehouse', 'Enterprise permission: warehouse.view'),
  ('webhook.manage', 'Webhook Manage', 'webhook', 'Enterprise permission: webhook.manage'),
  ('workflow.admin', 'Workflow Admin', 'workflow', 'Enterprise permission: workflow.admin'),
  ('workflow.manage', 'Workflow Manage', 'workflow', 'Enterprise permission: workflow.manage')
ON CONFLICT (code) DO NOTHING;
